stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.random_state
    - prepare.train_frac
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    params:
    - train.random_state
    - train.mode
  predict:
    cmd: python src/predict.py
    deps:
    - src/train.py
    params:
    - predict.model_name
    - predict.mode
